terminal.shell = "/usr/bin/zsh"

[window]

opacity = 0.9

padding.x = 10
padding.y = 10

decorations = "Full"
decorations_theme_variant = "Dark"

[font]

normal.family = "Jetbrains Mono Nerd Font"
bold.family = "Jetbrains Mono Nerd Font"
italic.family = "Jetbrains Mono Nerd Font"
bold_italic.family = "Jetbrains Mono Nerd Font"

size = 9.0

[scrolling]

history = 10000
multiplier = 3

[selection]

semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = false

[mouse]

hide_when_typing = true
